-- Ignore errors from DROP (e.g., if table doesn't exist)
WHENEVER SQLERROR CONTINUE;
DROP TABLE network_traffic PURGE;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Recreate the table
CREATE TABLE network_traffic (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    packet_size NUMBER,
    connection_time NUMBER,
    failed_logins NUMBER
);

-- Normal traffic
INSERT INTO network_traffic (packet_size, connection_time, failed_logins) VALUES (500, 12, 0);
INSERT INTO network_traffic (packet_size, connection_time, failed_logins) VALUES (512, 14, 0);
INSERT INTO network_traffic (packet_size, connection_time, failed_logins) VALUES (490, 11, 0);
-- Anomalous traffic (spike in size and failures)
INSERT INTO network_traffic (packet_size, connection_time, failed_logins) VALUES (9500, 120, 5);

COMMIT;
EXIT;