-- Drop old table (ignore errors)
WHENEVER SQLERROR CONTINUE;
DROP TABLE network_traffic PURGE;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Create directory object pointing to /tmp (where the CSV is copied)
CREATE OR REPLACE DIRECTORY data_dir AS '/tmp';

-- Create the final table with the five columns
CREATE TABLE network_traffic (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pixel_temp_C      NUMBER,
    lar_pressure_bar  NUMBER,
    lv_voltage_V      NUMBER,
    hv_current_uA     NUMBER,
    cooling_flow_lpm  NUMBER
);

-- PL/SQL block to read the CSV and insert rows (skips header)
DECLARE
    f UTL_FILE.FILE_TYPE;
    line VARCHAR2(4000);
    v_pixel_temp_C      NUMBER;
    v_lar_pressure_bar  NUMBER;
    v_lv_voltage_V      NUMBER;
    v_hv_current_uA     NUMBER;
    v_cooling_flow_lpm  NUMBER;
    first_row BOOLEAN := TRUE;
BEGIN
    -- Open the file (read mode)
    f := UTL_FILE.FOPEN('DATA_DIR', 'dcs_test.csv', 'R');
    LOOP
        BEGIN
            UTL_FILE.GET_LINE(f, line);
        EXCEPTION WHEN NO_DATA_FOUND THEN
            EXIT;
        END;
        IF first_row THEN
            first_row := FALSE;   -- skip header line
            CONTINUE;
        END IF;
        -- Parse comma‑separated values
        v_pixel_temp_C      := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 1));
        v_lar_pressure_bar  := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 2));
        v_lv_voltage_V      := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 3));
        v_hv_current_uA     := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 4));
        v_cooling_flow_lpm  := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 5));

        INSERT INTO network_traffic (pixel_temp_C, lar_pressure_bar, lv_voltage_V, hv_current_uA, cooling_flow_lpm)
        VALUES (v_pixel_temp_C, v_lar_pressure_bar, v_lv_voltage_V, v_hv_current_uA, v_cooling_flow_lpm);
    END LOOP;
    UTL_FILE.FCLOSE(f);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        IF UTL_FILE.IS_OPEN(f) THEN
            UTL_FILE.FCLOSE(f);
        END IF;
        RAISE;
END;
/
EXIT;