-- Ignore errors from DROP
WHENEVER SQLERROR CONTINUE;
DROP TABLE network_traffic PURGE;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Recreate the table
CREATE TABLE network_traffic (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    packet_size NUMBER,
    connection_time NUMBER,
    failed_logins NUMBER
);

-- Insert 5,000 synthetic rows
DECLARE
    v_packet_size NUMBER;
    v_connection_time NUMBER;
    v_failed_logins NUMBER;
BEGIN
    FOR i IN 1..5000 LOOP
        -- First 250 rows are ANOMALIES (~5%)
        IF i <= 250 THEN
            -- Large packet, long time, many failed logins
            v_packet_size := ROUND(6000 + DBMS_RANDOM.VALUE(0, 4000));   -- 6000–10000
            v_connection_time := ROUND(60 + DBMS_RANDOM.VALUE(0, 80));   -- 60–140 sec
            v_failed_logins := ROUND(3 + DBMS_RANDOM.VALUE(0, 5));       -- 3–8 failures
        ELSE
            -- Normal traffic: small packet, quick connection, almost no failures
            v_packet_size := ROUND(400 + DBMS_RANDOM.VALUE(0, 200));     -- 400–600
            v_connection_time := ROUND(5 + DBMS_RANDOM.VALUE(0, 20));    -- 5–25 sec
            v_failed_logins := ROUND(DBMS_RANDOM.VALUE(0, 1.5));         -- 0 or 1 failure
        END IF;

        -- Safety: ensure no negative values
        v_packet_size := GREATEST(10, v_packet_size);
        v_connection_time := GREATEST(1, v_connection_time);
        v_failed_logins := GREATEST(0, v_failed_logins);

        INSERT INTO network_traffic (packet_size, connection_time, failed_logins)
        VALUES (v_packet_size, v_connection_time, v_failed_logins);
    END LOOP;
    COMMIT;
END;
/
EXIT;