-- -- Ignore errors from DROP
-- WHENEVER SQLERROR CONTINUE;
-- DROP TABLE network_traffic PURGE;
-- WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- -- Recreate the table
-- CREATE TABLE network_traffic (
--     id NUMBER GENERATED BY DEFAULT AS IDENTITY,
--     packet_size NUMBER,
--     connection_time NUMBER,
--     failed_logins NUMBER
-- );

-- -- Insert 5,000 synthetic rows
-- DECLARE
--     v_packet_size NUMBER;
--     v_connection_time NUMBER;
--     v_failed_logins NUMBER;
-- BEGIN
--     FOR i IN 1..5000 LOOP
--         -- First 250 rows are ANOMALIES (~5%)
--         IF i <= 250 THEN
--             -- Large packet, long time, many failed logins
--             v_packet_size := ROUND(6000 + DBMS_RANDOM.VALUE(0, 4000));   -- 6000–10000
--             v_connection_time := ROUND(60 + DBMS_RANDOM.VALUE(0, 80));   -- 60–140 sec
--             v_failed_logins := ROUND(3 + DBMS_RANDOM.VALUE(0, 5));       -- 3–8 failures
--         ELSE
--             -- Normal traffic: small packet, quick connection, almost no failures
--             v_packet_size := ROUND(400 + DBMS_RANDOM.VALUE(0, 200));     -- 400–600
--             v_connection_time := ROUND(5 + DBMS_RANDOM.VALUE(0, 20));    -- 5–25 sec
--             v_failed_logins := ROUND(DBMS_RANDOM.VALUE(0, 1.5));         -- 0 or 1 failure
--         END IF;

--         -- Safety: ensure no negative values
--         v_packet_size := GREATEST(10, v_packet_size);
--         v_connection_time := GREATEST(1, v_connection_time);
--         v_failed_logins := GREATEST(0, v_failed_logins);

--         INSERT INTO network_traffic (packet_size, connection_time, failed_logins)
--         VALUES (v_packet_size, v_connection_time, v_failed_logins);
--     END LOOP;
--     COMMIT;
-- END;
-- /
-- EXIT;


-- Drop old table (ignore errors)
WHENEVER SQLERROR CONTINUE;
DROP TABLE network_traffic PURGE;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Create directory object pointing to /tmp (where the CSV is copied)
CREATE OR REPLACE DIRECTORY data_dir AS '/tmp';

-- Create the final table with the five columns
CREATE TABLE network_traffic (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pixel_temp_C      NUMBER,
    lar_pressure_bar  NUMBER,
    lv_voltage_V      NUMBER,
    hv_current_uA     NUMBER,
    cooling_flow_lpm  NUMBER
);

-- PL/SQL block to read the CSV and insert rows (skips header)
DECLARE
    f UTL_FILE.FILE_TYPE;
    line VARCHAR2(4000);
    v_pixel_temp_C      NUMBER;
    v_lar_pressure_bar  NUMBER;
    v_lv_voltage_V      NUMBER;
    v_hv_current_uA     NUMBER;
    v_cooling_flow_lpm  NUMBER;
    first_row BOOLEAN := TRUE;
BEGIN
    -- Open the file (read mode)
    f := UTL_FILE.FOPEN('DATA_DIR', 'dcs_test.csv', 'R');
    LOOP
        BEGIN
            UTL_FILE.GET_LINE(f, line);
        EXCEPTION WHEN NO_DATA_FOUND THEN
            EXIT;
        END;
        IF first_row THEN
            first_row := FALSE;   -- skip header line
            CONTINUE;
        END IF;
        -- Parse comma‑separated values
        v_pixel_temp_C      := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 1));
        v_lar_pressure_bar  := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 2));
        v_lv_voltage_V      := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 3));
        v_hv_current_uA     := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 4));
        v_cooling_flow_lpm  := TO_NUMBER(REGEXP_SUBSTR(line, '[^,]+', 1, 5));

        INSERT INTO network_traffic (pixel_temp_C, lar_pressure_bar, lv_voltage_V, hv_current_uA, cooling_flow_lpm)
        VALUES (v_pixel_temp_C, v_lar_pressure_bar, v_lv_voltage_V, v_hv_current_uA, v_cooling_flow_lpm);
    END LOOP;
    UTL_FILE.FCLOSE(f);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        IF UTL_FILE.IS_OPEN(f) THEN
            UTL_FILE.FCLOSE(f);
        END IF;
        RAISE;
END;
/
EXIT;